---
title: "Project 2"
output: 
 flexdashboard::flex_dashboard:
   orientation: rows
   vertical_layout: scroll
   source_code: embed
   theme: lumen
runtime: shiny
---

```{r context="setup", include=FALSE}
library(shiny)
library(ggplot2)
library(dplyr)
library(flexdashboard)
library(plotly)
require(rgdal)
require(leaflet)
require(readxl)
library(jsonlite) # fromJSON
library(utils) # URLencode functions
require(stringr)
require(leaflet.extras)
```

```{r, data_load, results='hide'}
railway_data   <- readOGR("./GBR_rails.shp", GDAL1_integer64_policy=TRUE)  # for lines map
admin_data     <- read.csv("GBR_adm2.csv")                                 # for poly map
admin.load     <- readOGR("./GBR_adm2.shp",  GDAL1_integer64_policy=TRUE)  # for poly map  
happiness_data <- read.csv("HappinessData.csv")    
```


```{r, cleaning}
admin_data        <- admin_data[ -c(2:5, 7, 9, 11:12) ]
names(admin_data) <- c("OBJECTID", "Country", "Area", "Type")
happiness_data    <- subset(happiness_data, happiness_data$Area!="City of London")

admin_data <-left_join(x = admin_data, y = happiness_data, by = "Area")

# Merge data on their respective IDs
admin      <- admin.load[admin.load$ID_2 %in% admin_data$OBJECTID,]
admin@data <- merge(admin@data, admin_data, sort=FALSE, by.x='ID_2', by.y='OBJECTID') %>%
  distinct(Area, .keep_all=TRUE)
```



Inputs {.sidebar}
=======================================================================

```{r context="render"}
checkboxGroupInput("countrySelect", "Country Filter:",
                   choices = c('England' = 'England',
                               'Northern Ireland' = 'Northern Ireland',
                               'Scotland' = 'Scotland',
                               'Wales' = 'Wales'),
                   selected = ('England'))
```


```{r context="render"}
checkboxGroupInput(inputId = 'Year',
                   label = "Select Year(s):",
                   choices = c('2011' = '2011',
                               '2012' = '2012',
                               '2013' = '2013',
                               '2014' = '2014',
                               '2015' = '2015',
                               '2016' = '2016'),
                   selected = ('2016'))
```


```{r}
admin_subset <- reactive({
  admin_data %>%
    filter(Year %in% input$Year | is.na(admin_data$Year))
})
```


```{r context="render"}
selectInput(inputId = 'x_input',
            label = "Plotting against Happiness:",
            choices = c('NoReligion' = 'NoReligion',
                        'NoSport' = 'NoSport',
                        'ChildhoodObesity' = 'ChildhoodObesity',
                        selected = 'NoSport'))
```

```{r context="render"}
output$downloadData <- downloadHandler(
  filename = function() {
    paste('data-', Sys.Date(), '.csv', sep='')
  },
    content = function(file) {
      write.csv(admin_subset(), file)
  }
)

downloadLink(outputId = "downloadData", label = "Download Data")
```


Maps R Us
=======================================================================





Row {}
-----------------------------------------------------------------------

```{r context="server"}
countryInputs <- reactive({
  admin2 <- subset(admin, Country == input$countrySelect)
  return(admin2)
  })

output$leaflet <- renderLeaflet({
  leaflet() %>%
    
    # Determine base maps
    addProviderTiles("OpenStreetMap.HOT", group = "Street Map") %>%
    addProviderTiles("Esri.WorldTerrain", group = "World Terrain Map") %>%
    
    # Add in layers control
    addLayersControl(
      baseGroups = c("Street Map", "World Terrain Map"),
      options = layersControlOptions(collapsed=FALSE))
   })

```

```{r context="render"}
observe({
  proxy <- leafletProxy("leaflet")
  
  proxy %>%
    clearShapes() %>%
    addPolygons(data = countryInputs(),color = "tomato", fillOpacity = 0.2, weight=2,
                highlightOptions = highlightOptions(color="White", bringToFront=TRUE),
                popup = ~paste0(countryInputs()$Area, ", ", countryInputs()$Happiness)) %>%
        addPolylines(data = railway_data, color = "black", weight=1, opacity=1)
  })
   
leafletOutput("leaflet")
   
```


Row {}
-----------------------------------------------------------------------

### Input-Based Plot

```{r context="server"}
output$InputBar <- renderPlotly({
  ggplotly(
    ggplot(subset(admin_subset(), !is.na(admin_subset()$Year)), 
           aes_string(x=paste0('reorder(Area, desc(Happiness))'), y=input$x_input, fill=paste0('as.integer(Happiness)'))) + 
      geom_bar(stat="identity", position=position_dodge()) + coord_flip() + theme(legend.position="none")
  )
})
```

```{r context="render"}
plotlyOutput('InputBar')
```

### Another plot1

```{r context="server"}
output$HappBar <- renderPlotly({
  ggplotly(
    ggplot(subset(admin_subset(), !is.na(admin_subset()$Year)), 
           aes(x=reorder(Area, desc(Happiness)), y=Happiness, fill=as.integer(Happiness))) +
      geom_bar(stat="identity", position=position_dodge()) + coord_flip() + theme(legend.position="none")
  )
})
```

```{r context="render"}
plotlyOutput('HappBar')
```

Ideally More Maps and MOre Plots
=======================================================================

### Another plot2

ggplot(subset(admin_subset, !is.na(admin_subset$Year)), aes(x=SuicideRates, y=Happiness, color=as.integer(Happiness))) + geom_point()

```{r context="server"}
output$InputPoint <- renderPlotly({
  ggplotly(
    ggplot(subset(admin_subset(), !is.na(admin_subset()$Year)), 
           aes_string(x=input$x_input, y='Happiness', color=paste0('as.integer(Happiness)'))) + 
      geom_point()
  )
})
```

```{r context="render"}
plotlyOutput('InputPoint')
```

Data Table
=======================================================================

### Happiness Dataset

```{r context="server"}
output$DataTable <- DT::renderDataTable({
  DT::datatable(admin_subset(), 
                options=list(pageLength=10), 
                rownames=FALSE)
  })
```

```{r context="render"}
DT::dataTableOutput('DataTable')
```

